name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows-build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Windows package
        run: npm run build:win

      - name: Locate installer
        id: find_installer
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Path dist -Filter '*.exe' -Recurse | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $exe) { throw 'No Windows installer (.exe) found in dist after build.' }
          "installer=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: ${{ steps.find_installer.outputs.installer }}
