name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows-build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y wine64 wine32 mono-devel

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Windows package
        run: npm run build:win

      - name: Locate installer
        id: find_installer
        run: |
          set -euo pipefail
          installer=$(find dist -type f -name '*.exe' -print -quit)
          if [ -z "$installer" ]; then
            echo "No Windows installer (.exe) found in dist after build." >&2
            exit 1
          fi
          echo "installer=$installer" >> "$GITHUB_OUTPUT"

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: ${{ steps.find_installer.outputs.installer }}
